### ISSUE TITLE
Discussion Board for Website, Course Contents and Activities

### ISSUE THREAD

**Issue by girlscript** [girlscript/contribute-girlscript#2]
A brief list of features that the website would primarily involve:

Registration for new members
Login for enrolled people
Course Content section containing various courses that can be learnt online after logging in
Get Inspired section for publishing interviews
Technical Blogs Sections for writing and publishing blogs
Gallery for photographs of last events
A Wall of Fame section for 'Contributor of the Month'
An online chat room for clearing doubts and queries

Feel free to suggest changes, improvements, or more ideas for features to be included in the website.
Thanks! 😄

**Comment by girlscript** [comment]
Also, for course contents-
The course contents should be technical
It can be easily learnt by any beginner
The content must be original

The games or activities that can be included for offline workshops must teach something technical or should be inspirational. motivating the students who are attending our workshops.

**Comment by jgmac1106** [comment]
I created a Known site for coderdojo erode. Its ooen source and has multi membership platform. 

We could also use a WordPress install.

Another idea might be Mahara, an open source social network/portfolio platform. 

Or do a front facing website and  a Discourse install ($10 a month US). 

My company ReVIEW Talent Feedback System would be willing to donate the server cost, domain registration, and help build out the site.

**Comment by girlscript** [comment]
Hello @jgmac1106 , thank you so much for valuable suggestions. We would really love to have further discussion with you. The front facing website with a Discourse install would be great or we can choose any other options. Can I get your email address or any other contact where our team members can connect with you?

**Comment by jgmac1106** [comment]
jgregmcverry@gmail.com It is getting late your time but I can connect with you any time early EDT.

**Comment by siddhartharao17** [comment]
Hi @jgmac1106 I like the discourse idea for forums and it's also convenient and easy to use. I'm on the EDT timezone as well.

**Comment by siddhartharao17** [comment]
Btw, can't we do wordpress themes for front and discourse combination? If that's possible, we would be done with forums, front end and blogging.

**Comment by girlscript** [comment]
Yes! The idea of using WordPress with Discourse is great.  We will have blogs alongwith a discussion forum. All that we need

**Comment by jgmac1106** [comment]
Discourse is ten dollars a month. Check out http://edu106.networkedlearningcollaborative.com

That is Known which we can install for free. Could add a Telegram group to it. 

Or we use a mukti member WordPress group. 

Steo one before deciding on tech is paper. Storyboard out what you want on website. Know the pages and navigation. Will. Start a new issue for this.

**Comment by jgmac1106** [comment]
Issue #5 already exists. Nice job.
